### ISSUE TITLE
Message writing area overlapping chats

### ISSUE THREAD

**Issue by hacker20028** [theindianappguy/FlutterChatAppTutorial#10] opened 2021-02-04 03:15 UTC
The message area where the messages are typed is overlapping the chats making the chats not visible and not readable . Also the Conversation screen should automatically go down to the latest message. Kindly help with them. I also want to add Time stamps in chats .
![IMG_20210204_084407](https://user-images.githubusercontent.com/40013389/106839990-49579880-66c5-11eb-8e6d-305628dafe84.jpg)

**Comment by MAH0460** [comment] 2021-02-13 16:22
Inside the chatMessageList widget
after we return the snapshot.hasdata
and before child: ListView.builder
add a line
margin: EdgeInsets.only(bottom : 80),

**Comment by MAH0460** [comment] 2021-02-13 16:33
To add time stamp add an additional variable for time in the database and retrive it each time and print below the messages.

**Comment by hacker20028** [comment] 2021-02-13 20:06
> To add time stamp add an additional variable for time in the database and retrive it each time and print below the messages.

Can you guide me with that?

**Comment by hacker20028** [comment] 2021-02-13 22:17
> Inside the chatMessageList widget
> after we return the snapshot.hasdata
> and before child: ListView.builder
> add a line
> margin: EdgeInsets.only(bottom : 80),
> 
> And for going to the latest message
> add a line
> inside the child: ListView.builder
> reverse: true,
> 
> Like this
> ![Screenshot (21)](https://user-images.githubusercontent.com/58516674/107855088-666b3480-6e46-11eb-8614-7cedfc56ee35.png)
> 
> 

Adding 'reverse: true' is taking the lastest message on top instead in bottom as can be seen in the screenshot and getting the screen to bottom
![Screenshot_2021-02-14-03-44-57-66_93e0e11aadf2f1b67248ea93df5197d4.jpg](https://user-images.githubusercontent.com/40013389/107863071-44d67100-6e77-11eb-8c57-7ed5d18642a8.jpg)

**Comment by MAH0460** [comment] 2021-02-14 00:57
Add Descending: true in orderby
![Screenshot (22)](https://user-images.githubusercontent.com/58516674/107865552-a9042f80-6e8d-11eb-8c99-b00eb55ac94f.png)

**Comment by MAH0460** [comment] 2021-02-15 16:17
Please close the issue if the problem is solved.

**Comment by hacker20028** [comment] 2021-02-15 17:36
> To add time stamp add an additional variable for time in the database and retrive it each time and print below the messages.

Any guide on this?

**Comment by MAH0460** [comment] 2021-02-17 06:45
https://github.com/theindianappguy/FlutterChatAppTutorial/issues/8#issuecomment-780343169

**Comment by hacker20028** [comment] 2021-02-17 14:27
> [#8 (comment)](https://github.com/theindianappguy/FlutterChatAppTutorial/issues/8#issuecomment-780343169)
> This is the link.

![ss](https://user-images.githubusercontent.com/40013389/108218054-485d4700-715a-11eb-9a8c-87d08460d6ca.PNG)
I am Getting the above errors

**Comment by hacker20028** [comment] 2021-02-17 14:32
> > [#8 (comment)](https://github.com/theindianappguy/FlutterChatAppTutorial/issues/8#issuecomment-780343169)
> > This is the link.
> 
> ![ss](https://user-images.githubusercontent.com/40013389/108218054-485d4700-715a-11eb-9a8c-87d08460d6ca.PNG)
> I am Getting the above errors

Fixed the _x problem

**Comment by hacker20028** [comment] 2021-02-17 14:39
> > > [#8 (comment)](https://github.com/theindianappguy/FlutterChatAppTutorial/issues/8#issuecomment-780343169)
> > > This is the link.
> > 
> > 
> > ![ss](https://user-images.githubusercontent.com/40013389/108218054-485d4700-715a-11eb-9a8c-87d08460d6ca.PNG)
> > I am Getting the above errors
> 
> Fixed the _x problem by adding String _x;

**Closed** 2021-02-18 08:12 UTC
